/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Guillermo (https://sketchfab.com/guillermosainz)
license: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
source: https://sketchfab.com/3d-models/basquiat-graffiti-art-wall-fbd390f2dbb046ef9d6b0b2d9a917093
title: Basquiat Graffiti Art Wall
*/

import React, {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
} from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();

export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/basquiat_graffiti_art_wall.glb"
  );

  const instances = useMemo(
    () => ({
      Object: glb.nodes.Object_2,
      Object1: glb.nodes.Object_3,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    glb.scene.traverse((child) => {
      child.castShadow = true;
    });

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged scale={[0.75, 0.75, 0.75]} meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function BasquiatArtWall(props) {
  const instances = useContext(context);
  const ref = useRef();

  useEffect(() => {
    if (ref.current) {
      ref.current.traverse((child) => {
        child.castShadow = true;
        child.receiveShadow = true;
      });
    }
  }, []);

  return (
    <group ref={ref} {...props} dispose={null}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name='cropped_textured_meshobjcleanermaterialmergergles'
          userData={{
            name: "cropped_textured_mesh.obj.cleaner.materialmerger.gles",
          }}
        >
          <instances.Object name='Object_2' userData={{ name: "Object_2" }} />
          <instances.Object1 name='Object_3' userData={{ name: "Object_3" }} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/basquiat_graffiti_art_wall.glb"
);
