/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AG3D _-=-_ Follow me in Instagram: ag3d_design (https://sketchfab.com/gordillo.antonio.j)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chicago-dancing-113e07fec8ed46e19854a89dbe56afc3
title: CHICAGO Dancing
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Chicago_dancing(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/chicago_dancing-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["mixamo.com"].reset().fadeIn(0.5).play();
  }, []);

  return (
    <group castShadow ref={group} {...props} dispose={null}>
      <group castShadow name='Sketchfab_Scene'>
        <group
          castShadow
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group
            castShadow
            name='8f02c993fde445208bb55ba608acf9a3fbx'
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: "8f02c993fde445208bb55ba608acf9a3.fbx" }}
          >
            <group castShadow name='Object_2' userData={{ name: "Object_2" }}>
              <group castShadow name='RootNode' userData={{ name: "RootNode" }}>
                <group
                  castShadow
                  name='Object_4'
                  userData={{ name: "Object_4" }}
                >
                  <primitive
                    castShadow
                    object={nodes._rootJoint}
                    receiveShadow
                  />
                  <skinnedMesh
                    castShadow
                    receiveShadow
                    name='Object_6'
                    geometry={nodes.Object_6.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_6.skeleton}
                    userData={{ name: "Object_6" }}
                  />
                  <skinnedMesh
                    castShadow
                    receiveShadow
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_7.skeleton}
                    userData={{ name: "Object_7" }}
                  />
                  <skinnedMesh
                    name='Object_9'
                    geometry={nodes.Object_9.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_9.skeleton}
                    userData={{ name: "Object_9" }}
                  />
                  <skinnedMesh
                    name='Object_10'
                    geometry={nodes.Object_10.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_10.skeleton}
                    userData={{ name: "Object_10" }}
                  />
                  <skinnedMesh
                    name='Object_11'
                    geometry={nodes.Object_11.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_11.skeleton}
                    userData={{ name: "Object_11" }}
                  />
                  <skinnedMesh
                    name='Object_12'
                    geometry={nodes.Object_12.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_12.skeleton}
                    userData={{ name: "Object_12" }}
                  />
                  <skinnedMesh
                    name='Object_14'
                    geometry={nodes.Object_14.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_14.skeleton}
                    userData={{ name: "Object_14" }}
                  />
                  <skinnedMesh
                    name='Object_15'
                    geometry={nodes.Object_15.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_15.skeleton}
                    userData={{ name: "Object_15" }}
                  />
                  <skinnedMesh
                    name='Object_16'
                    geometry={nodes.Object_16.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_16.skeleton}
                    userData={{ name: "Object_16" }}
                  />
                  <skinnedMesh
                    name='Object_18'
                    geometry={nodes.Object_18.geometry}
                    material={materials["Scene_-_Root"]}
                    skeleton={nodes.Object_18.skeleton}
                    userData={{ name: "Object_18" }}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/chicago_dancing-transformed.glb"
);
