/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Khodrin (https://sketchfab.com/Khodrin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/christmas-hat-9df9e5041a48418ca9691045b4e59730
title: Christmas Hat
*/

import React, { useMemo, useContext, createContext, useEffect } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/christmas_hat.glb"
  );
  const instances = useMemo(
    () => ({
      Object: glb.nodes.Object_11,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    glb.scene.traverse((child) => {
      child.castShadow = true;
    });

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function ChristmasHat(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name='9cc958f154bb47d28b5326de72cd644afbx'
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "9cc958f154bb47d28b5326de72cd644a.fbx" }}
        >
          <group name='RootNode' userData={{ name: "RootNode" }}>
            <group
              name='Armature'
              // rotation={[-Math.PI / 2, 0, 0]}
              userData={{ name: "Armature" }}
            >
              <group name='Object_4' userData={{ name: "Object_4" }}>
                {/* <primitive object={nodes._rootJoint} /> */}
                <instances.Object
                  name='Object_11'
                  userData={{ name: "Object_11" }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(import.meta.env.VITE_ASSETS_PATH + "/models/christmas_hat.glb");
