/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: patrakeevasveta (https://sketchfab.com/patrakeevasveta)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/neon-christmas-tree-day-12-e6bdaa83cdda4978900ace37e9de20f3
title: Neon christmas tree - Day 12
*/

import React, {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
} from "react";
import { useGLTF, Merged, useAnimations } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH +
      "/models/neon_christmas_tree_-_day_12.glb"
  );
  const instances = useMemo(
    () => ({
      Object: glb.nodes.Object_4,
      Object1: glb.nodes.Object_6,
      Object2: glb.nodes.Object_8,
      Object3: glb.nodes.Object_10,
      Object4: glb.nodes.Object_12,
      Object5: glb.nodes.Object_14,
      Object6: glb.nodes.Object_16,
      Object7: glb.nodes.Object_18,
      Object8: glb.nodes.Object_20,
      Object9: glb.nodes.Object_22,
      Object10: glb.nodes.Object_24,
      Object11: glb.nodes.Object_26,
      Object12: glb.nodes.Object_28,
      Object13: glb.nodes.Object_30,
      Object14: glb.nodes.Object_32,
      Object15: glb.nodes.Object_42,
      Object16: glb.nodes.Object_44,
      Object17: glb.nodes.Object_46,
      Object18: glb.nodes.Object_48,
      Object19: glb.nodes.Object_50,
      Object20: glb.nodes.Object_52,
      Object21: glb.nodes.Object_54,
      Object22: glb.nodes.Object_56,
      Object23: glb.nodes.Object_34,
      Object24: glb.nodes.Object_36,
      Object25: glb.nodes.Object_38,
      Object26: glb.nodes.Object_40,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    glb.scene.traverse((child) => {
      child.castShadow = true;
    });

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function ChristmasTree(props) {
  const instances = useContext(context);
  const group = useRef();
  // const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.46}
          userData={{ name: "Sketchfab_model" }}
        >
          <group name='root' userData={{ name: "root" }}>
            <group
              name='GLTF_SceneRootNode'
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: "GLTF_SceneRootNode" }}
            >
              <group
                name='rings005_0'
                position={[-0.68, 2.37, 0.28]}
                userData={{ name: "rings.005_0" }}
              >
                <instances.Object
                  name='Object_4'
                  userData={{ name: "Object_4" }}
                />
              </group>
              <group
                name='rings001_1'
                position={[-0.52, 3.02, -0.11]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.001_1" }}
              >
                <instances.Object1
                  name='Object_6'
                  userData={{ name: "Object_6" }}
                />
              </group>
              <group
                name='rings002_2'
                position={[0.68, 2.83, 0.22]}
                rotation={[0, 0.13, 0]}
                userData={{ name: "rings.002_2" }}
              >
                <instances.Object2
                  name='Object_8'
                  userData={{ name: "Object_8" }}
                />
              </group>
              <group
                name='rings003_3'
                position={[1.05, 2.18, -0.06]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.003_3" }}
              >
                <instances.Object3
                  name='Object_10'
                  userData={{ name: "Object_10" }}
                />
              </group>
              <group
                name='rings004_4'
                position={[0.79, 1.75, 0.27]}
                rotation={[0, 0.13, 0]}
                userData={{ name: "rings.004_4" }}
              >
                <instances.Object4
                  name='Object_12'
                  userData={{ name: "Object_12" }}
                />
              </group>
              <group
                name='rings006_5'
                position={[1.24, 1.37, 0.05]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.006_5" }}
              >
                <instances.Object5
                  name='Object_14'
                  userData={{ name: "Object_14" }}
                />
              </group>
              <group
                name='rings007_6'
                position={[1.63, 1.06, -0.22]}
                rotation={[0, 0.13, 0]}
                userData={{ name: "rings.007_6" }}
              >
                <instances.Object6
                  name='Object_16'
                  userData={{ name: "Object_16" }}
                />
              </group>
              <group
                name='rings008_7'
                position={[1.66, 0.29, -0.16]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.008_7" }}
              >
                <instances.Object7
                  name='Object_18'
                  userData={{ name: "Object_18" }}
                />
              </group>
              <group
                name='rings009_8'
                position={[1.44, -0.14, 0.24]}
                rotation={[0, 0.06, 0]}
                userData={{ name: "rings.009_8" }}
              >
                <instances.Object8
                  name='Object_20'
                  userData={{ name: "Object_20" }}
                />
              </group>
              <group
                name='rings010_9'
                position={[0.89, -0.25, -0.31]}
                rotation={[0, -0.06, 0]}
                userData={{ name: "rings.010_9" }}
              >
                <instances.Object9
                  name='Object_22'
                  userData={{ name: "Object_22" }}
                />
              </group>
              <group
                name='rings011_10'
                position={[-1.2, -0.06, 0.48]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.011_10" }}
              >
                <instances.Object10
                  name='Object_24'
                  userData={{ name: "Object_24" }}
                />
              </group>
              <group
                name='rings012_11'
                position={[-1.67, -0.07, 0.05]}
                rotation={[0, 0.13, 0]}
                userData={{ name: "rings.012_11" }}
              >
                <instances.Object11
                  name='Object_26'
                  userData={{ name: "Object_26" }}
                />
              </group>
              <group
                name='rings013_12'
                position={[-1.76, 0.72, -0.24]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.013_12" }}
              >
                <instances.Object12
                  name='Object_28'
                  userData={{ name: "Object_28" }}
                />
              </group>
              <group
                name='rings014_13'
                position={[-1.19, 1.4, 0.64]}
                rotation={[0, 0.13, 0]}
                userData={{ name: "rings.014_13" }}
              >
                <instances.Object13
                  name='Object_30'
                  userData={{ name: "Object_30" }}
                />
              </group>
              <group
                name='rings015_14'
                position={[-1.36, 2.01, -0.18]}
                rotation={[0, -0.13, 0]}
                userData={{ name: "rings.015_14" }}
              >
                <instances.Object14
                  name='Object_32'
                  userData={{ name: "Object_32" }}
                />
              </group>
              <group
                name='star001_19'
                position={[0.28, 2.61, 0]}
                userData={{ name: "star.001_19" }}
              >
                <instances.Object15
                  name='Object_42'
                  userData={{ name: "Object_42" }}
                />
              </group>
              <group
                name='star002_20'
                position={[0.19, 2.96, 0]}
                userData={{ name: "star.002_20" }}
              >
                <instances.Object16
                  name='Object_44'
                  userData={{ name: "Object_44" }}
                />
              </group>
              <group
                name='star003_21'
                position={[-0.19, 2.96, 0]}
                userData={{ name: "star.003_21" }}
              >
                <instances.Object17
                  name='Object_46'
                  userData={{ name: "Object_46" }}
                />
              </group>
              <group
                name='star004_22'
                position={[-0.28, 2.61, 0]}
                userData={{ name: "star.004_22" }}
              >
                <instances.Object18
                  name='Object_48'
                  userData={{ name: "Object_48" }}
                />
              </group>
              <group
                name='gifts_23'
                position={[0.29, -0.57, 0.14]}
                userData={{ name: "gifts_23" }}
              >
                <instances.Object19
                  name='Object_50'
                  userData={{ name: "Object_50" }}
                />
              </group>
              <group
                name='gifts001_24'
                position={[1.21, -0.57, 0]}
                rotation={[0, Math.PI / 4, 0]}
                userData={{ name: "gifts.001_24" }}
              >
                <instances.Object20
                  name='Object_52'
                  userData={{ name: "Object_52" }}
                />
              </group>
              <group
                name='gifts002_25'
                position={[-1.51, -0.56, 0]}
                userData={{ name: "gifts.002_25" }}
              >
                <instances.Object21
                  name='Object_54'
                  userData={{ name: "Object_54" }}
                />
              </group>
              <group
                name='gifts003_26'
                position={[-0.74, -0.57, -0.28]}
                rotation={[0, Math.PI / 4, 0]}
                userData={{ name: "gifts.003_26" }}
              >
                <instances.Object22
                  name='Object_56'
                  userData={{ name: "Object_56" }}
                />
              </group>
              <group name='tree_15' userData={{ name: "tree_15" }}>
                <instances.Object23
                  name='Object_34'
                  userData={{ name: "Object_34" }}
                />
              </group>
              <group name='base_16' userData={{ name: "base_16" }}>
                <instances.Object24
                  name='Object_36'
                  userData={{ name: "Object_36" }}
                />
              </group>
              <group
                name='star_17'
                position={[0, 2.73, 0]}
                userData={{ name: "star_17" }}
              >
                <instances.Object25
                  name='Object_38'
                  userData={{ name: "Object_38" }}
                />
              </group>
              <group
                name='tree001_18'
                position={[-0.04, 0.06, -0.01]}
                userData={{ name: "tree.001_18" }}
              >
                <instances.Object26
                  name='Object_40'
                  userData={{ name: "Object_40" }}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/neon_christmas_tree_-_day_12.glb"
);
