/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Juan Carlos (https://sketchfab.com/grove4069)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/christmas-balls-06e4f260bbf64d2abeca609d78eb164a
title: Christmas balls!
*/

import React, { useMemo, useContext, createContext, useEffect } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/christmas_balls.glb"
  );
  const instances = useMemo(
    () => ({
      Pallinanatalizia: glb.nodes.Pallina_natalizia_01_0,
      Pallinanatalizia1: glb.nodes.Pallina_natalizia_01_1,
      Gancettopallinenatalizie: glb.nodes.Gancetto_palline_natalizie_01_0,
      Pallinanatalizia2: glb.nodes.Pallina_natalizia_02_0,
      Pallinanatalizia3: glb.nodes.Pallina_natalizia_02_1,
      Pallinanatalizia4: glb.nodes.Pallina_natalizia_02_2,
      Pallinanatalizia5: glb.nodes.Pallina_natalizia_02_3,
      Pallinanatalizia6: glb.nodes.Pallina_natalizia_03_0,
      Pallinanatalizia7: glb.nodes.Pallina_natalizia_03_1,
      Pallinanatalizia8: glb.nodes.Pallina_natalizia_04_0,
      Pallinanatalizia9: glb.nodes.Pallina_natalizia_04_1,
      Pallinanatalizia10: glb.nodes.Pallina_natalizia_04_2,
      Pallinanatalizia11: glb.nodes.Pallina_natalizia_04_3,
      Pallinanatalizia12: glb.nodes.Pallina_natalizia_05_0,
      Pallinanatalizia13: glb.nodes.Pallina_natalizia_05_1,
      Pallinanatalizia14: glb.nodes.Pallina_natalizia_05_2,
      Filointrecciato: glb.nodes.Filo_intrecciato001_0,
      Filointrecciato1: glb.nodes.Filo_intrecciato001_1,
      Pallinanatalizia15: glb.nodes.Pallina_natalizia_06_0,
      Pallinanatalizia16: glb.nodes.Pallina_natalizia_06_1,
      Pallinanatalizia17: glb.nodes.Pallina_natalizia_09_0,
      Pallinanatalizia18: glb.nodes.Pallina_natalizia_09_1,
      Pallinanatalizia19: glb.nodes.Pallina_natalizia_08_0,
      Pallinanatalizia20: glb.nodes.Pallina_natalizia_08_1,
      Pallinanatalizia21: glb.nodes.Pallina_natalizia_07_0,
      Pallinanatalizia22: glb.nodes.Pallina_natalizia_07_1,
      Pallinanatalizia23: glb.nodes.Pallina_natalizia_07_2,
      Pallinanatalizia24: glb.nodes.Pallina_natalizia_07_3,
      Pallinanatalizia25: glb.nodes.Pallina_natalizia_10_0,
      Pallinanatalizia26: glb.nodes.Pallina_natalizia_10_1,
      Pallinanatalizia27: glb.nodes.Pallina_natalizia_11_0,
      Pallinanatalizzia: glb.nodes.Pallina_natalizzia_12_0,
      Pallinanatalizzia1: glb.nodes.Pallina_natalizzia_12_1,
      Pallinanatalizzia2: glb.nodes.Pallina_natalizzia_12_2,
      Pallinanatalizzia3: glb.nodes.Pallina_natalizzia_12_3,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function ChristmasBalls(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group name='Root' userData={{ name: "Root" }}>
          <group
            name='Pallina_natalizia_01'
            position={[-0.4, -0.08, -0.08]}
            userData={{ name: "Pallina_natalizia_01" }}
          >
            <instances.Pallinanatalizia
              name='Pallina_natalizia_01_0'
              userData={{ name: "Pallina_natalizia_01_0" }}
            />
            <instances.Pallinanatalizia1
              name='Pallina_natalizia_01_1'
              userData={{ name: "Pallina_natalizia_01_1" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_01'
            position={[-0.39, -0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_01" }}
          >
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_01_0'
              userData={{ name: "Gancetto_palline_natalizie_01_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_02'
            position={[-0.23, -0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_02" }}
          >
            <group
              name='Pallina_natalizia_02'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_02" }}
            >
              <instances.Pallinanatalizia2
                name='Pallina_natalizia_02_0'
                userData={{ name: "Pallina_natalizia_02_0" }}
              />
              <instances.Pallinanatalizia3
                name='Pallina_natalizia_02_1'
                userData={{ name: "Pallina_natalizia_02_1" }}
              />
              <instances.Pallinanatalizia4
                name='Pallina_natalizia_02_2'
                userData={{ name: "Pallina_natalizia_02_2" }}
              />
              <instances.Pallinanatalizia5
                name='Pallina_natalizia_02_3'
                userData={{ name: "Pallina_natalizia_02_3" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_02_0'
              userData={{ name: "Gancetto_palline_natalizie_02_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_03'
            position={[-0.07, -0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_03" }}
          >
            <group
              name='Pallina_natalizia_03'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_03" }}
            >
              <instances.Pallinanatalizia6
                name='Pallina_natalizia_03_0'
                userData={{ name: "Pallina_natalizia_03_0" }}
              />
              <instances.Pallinanatalizia7
                name='Pallina_natalizia_03_1'
                userData={{ name: "Pallina_natalizia_03_1" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_03_0'
              userData={{ name: "Gancetto_palline_natalizie_03_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_04'
            position={[-0.39, 0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_04" }}
          >
            <group
              name='Pallina_natalizia_04'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_04" }}
            >
              <instances.Pallinanatalizia8
                name='Pallina_natalizia_04_0'
                userData={{ name: "Pallina_natalizia_04_0" }}
              />
              <instances.Pallinanatalizia9
                name='Pallina_natalizia_04_1'
                userData={{ name: "Pallina_natalizia_04_1" }}
              />
              <instances.Pallinanatalizia10
                name='Pallina_natalizia_04_2'
                userData={{ name: "Pallina_natalizia_04_2" }}
              />
              <instances.Pallinanatalizia11
                name='Pallina_natalizia_04_3'
                userData={{ name: "Pallina_natalizia_04_3" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_04_0'
              userData={{ name: "Gancetto_palline_natalizie_04_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_05'
            position={[-0.23, 0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_05" }}
          >
            <group
              name='Pallina_natalizia_05'
              position={[-0.01, 0, -0.1]}
              scale={[0.77, 0.77, 1]}
              userData={{ name: "Pallina_natalizia_05" }}
            >
              <instances.Pallinanatalizia12
                name='Pallina_natalizia_05_0'
                userData={{ name: "Pallina_natalizia_05_0" }}
              />
              <instances.Pallinanatalizia13
                name='Pallina_natalizia_05_1'
                userData={{ name: "Pallina_natalizia_05_1" }}
              />
              <instances.Pallinanatalizia14
                name='Pallina_natalizia_05_2'
                userData={{ name: "Pallina_natalizia_05_2" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_05_0'
              userData={{ name: "Gancetto_palline_natalizie_05_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_06'
            position={[-0.07, 0.08, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_06" }}
          >
            <group
              name='Filo_intrecciato001'
              position={[-0.01, 0, -0.1]}
              scale={0.01}
              userData={{ name: "Filo_intrecciato.001" }}
            >
              <instances.Filointrecciato
                name='Filo_intrecciato001_0'
                userData={{ name: "Filo_intrecciato.001_0" }}
              />
              <instances.Filointrecciato1
                name='Filo_intrecciato001_1'
                userData={{ name: "Filo_intrecciato.001_1" }}
              />
            </group>
            <group
              name='Pallina_natalizia_06'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_06" }}
            >
              <instances.Pallinanatalizia15
                name='Pallina_natalizia_06_0'
                userData={{ name: "Pallina_natalizia_06_0" }}
              />
              <instances.Pallinanatalizia16
                name='Pallina_natalizia_06_1'
                userData={{ name: "Pallina_natalizia_06_1" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_06_0'
              userData={{ name: "Gancetto_palline_natalizie_06_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_09'
            position={[-0.07, 0.24, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_09" }}
          >
            <group
              name='Pallina_natalizia_09'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_09" }}
            >
              <instances.Pallinanatalizia17
                name='Pallina_natalizia_09_0'
                userData={{ name: "Pallina_natalizia_09_0" }}
              />
              <instances.Pallinanatalizia18
                name='Pallina_natalizia_09_1'
                userData={{ name: "Pallina_natalizia_09_1" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_09_0'
              userData={{ name: "Gancetto_palline_natalizie_09_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_08'
            position={[-0.23, 0.24, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_08" }}
          >
            <group
              name='Pallina_natalizia_08'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_08" }}
            >
              <instances.Pallinanatalizia19
                name='Pallina_natalizia_08_0'
                userData={{ name: "Pallina_natalizia_08_0" }}
              />
              <instances.Pallinanatalizia20
                name='Pallina_natalizia_08_1'
                userData={{ name: "Pallina_natalizia_08_1" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_08_0'
              userData={{ name: "Gancetto_palline_natalizie_08_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_07'
            position={[-0.39, 0.24, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_07" }}
          >
            <group
              name='Pallina_natalizia_07'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_07" }}
            >
              <instances.Pallinanatalizia21
                name='Pallina_natalizia_07_0'
                userData={{ name: "Pallina_natalizia_07_0" }}
              />
              <instances.Pallinanatalizia22
                name='Pallina_natalizia_07_1'
                userData={{ name: "Pallina_natalizia_07_1" }}
              />
              <instances.Pallinanatalizia23
                name='Pallina_natalizia_07_2'
                userData={{ name: "Pallina_natalizia_07_2" }}
              />
              <instances.Pallinanatalizia24
                name='Pallina_natalizia_07_3'
                userData={{ name: "Pallina_natalizia_07_3" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_07_0'
              userData={{ name: "Gancetto_palline_natalizie_07_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_10'
            position={[-0.39, 0.4, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_10" }}
          >
            <group
              name='Pallina_natalizia_10'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_10" }}
            >
              <instances.Pallinanatalizia25
                name='Pallina_natalizia_10_0'
                userData={{ name: "Pallina_natalizia_10_0" }}
              />
              <instances.Pallinanatalizia26
                name='Pallina_natalizia_10_1'
                userData={{ name: "Pallina_natalizia_10_1" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_10_0'
              userData={{ name: "Gancetto_palline_natalizie_10_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_11'
            position={[-0.23, 0.4, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_11" }}
          >
            <group
              name='Pallina_natalizia_11'
              position={[-0.01, 0, -0.1]}
              userData={{ name: "Pallina_natalizia_11" }}
            >
              <instances.Pallinanatalizia27
                name='Pallina_natalizia_11_0'
                userData={{ name: "Pallina_natalizia_11_0" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_11_0'
              userData={{ name: "Gancetto_palline_natalizie_11_0" }}
            />
          </group>
          <group
            name='Gancetto_palline_natalizie_12'
            position={[-0.07, 0.4, 0.02]}
            userData={{ name: "Gancetto_palline_natalizie_12" }}
          >
            <group
              name='Pallina_natalizzia_12'
              position={[-0.01, 0, -0.02]}
              userData={{ name: "Pallina_natalizzia_12" }}
            >
              <instances.Pallinanatalizzia
                name='Pallina_natalizzia_12_0'
                userData={{ name: "Pallina_natalizzia_12_0" }}
              />
              <instances.Pallinanatalizzia1
                name='Pallina_natalizzia_12_1'
                userData={{ name: "Pallina_natalizzia_12_1" }}
              />
              <instances.Pallinanatalizzia2
                name='Pallina_natalizzia_12_2'
                userData={{ name: "Pallina_natalizzia_12_2" }}
              />
              <instances.Pallinanatalizzia3
                name='Pallina_natalizzia_12_3'
                userData={{ name: "Pallina_natalizzia_12_3" }}
              />
            </group>
            <instances.Gancettopallinenatalizie
              name='Gancetto_palline_natalizie_12_0'
              userData={{ name: "Gancetto_palline_natalizie_12_0" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/christmas_balls.glb"
);
