/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: carlcapu9 (https://sketchfab.com/carlcapu9)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/cocaine-pack-9daea520e32a43579e15c0fa4ce60146
title: Cocaine Pack
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cocaine_pack(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/cocaine_pack-transformed.glb"
  );
  return (
    <group {...props} dispose={null} rotation-y={Math.PI / -2}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name='4f7e934cceaf4691b68356311a7d7c1dfbx'
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "4f7e934cceaf4691b68356311a7d7c1d.fbx" }}
        >
          <group name='RootNode' userData={{ name: "RootNode" }}>
            <group
              name='Cube003'
              position={[84.12, 130.22, 266.81]}
              rotation={[Math.PI / 2, 0, 2.09]}
              scale={62.28}
              userData={{ name: "Cube.003" }}
            >
              <mesh
                name='Cube003_Cocaine_pack_0'
                geometry={nodes.Cube003_Cocaine_pack_0.geometry}
                material={materials.Cocaine_pack}
                userData={{ name: "Cube.003_Cocaine pack_0" }}
              />
            </group>
            <group
              name='Cube'
              position={[84.57, 135.2, 267.36]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
              userData={{ name: "Cube" }}
            >
              <mesh
                name='Cube_money_side_0'
                geometry={nodes.Cube_money_side_0.geometry}
                material={materials.money_side}
                userData={{ name: "Cube_money side_0" }}
              />
              <mesh
                name='Cube_100_dollar_front_0'
                geometry={nodes.Cube_100_dollar_front_0.geometry}
                material={materials["100_dollar_front"]}
                userData={{ name: "Cube_100 dollar front_0" }}
              />
              <mesh
                name='Cube_band_0'
                geometry={nodes.Cube_band_0.geometry}
                material={materials.band}
                userData={{ name: "Cube_band_0" }}
              />
              <mesh
                name='Cube_100_dollar_back_0'
                geometry={nodes.Cube_100_dollar_back_0.geometry}
                material={materials["100_dollar_back"]}
                userData={{ name: "Cube_100 dollar back_0" }}
              />
            </group>
            <group
              name='bancale_coca'
              position={[30.88, 75.7, 9.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[98.06, 98.71, 96.21]}
              userData={{ name: "bancale coca" }}
            >
              <mesh
                name='bancale_coca_Plastic001_0'
                geometry={nodes.bancale_coca_Plastic001_0.geometry}
                material={materials["Plastic.001"]}
                userData={{ name: "bancale coca_Plastic.001_0" }}
              />
              <mesh
                name='bancale_coca_Bancale001_0'
                geometry={nodes.bancale_coca_Bancale001_0.geometry}
                material={materials["Bancale.001"]}
                userData={{ name: "bancale coca_Bancale.001_0" }}
              />
            </group>
            <group
              name='bancale_coca_broken'
              position={[28.1, 75.7, 320.97]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[98.06, 98.71, 96.21]}
              userData={{ name: "bancale coca broken" }}
            >
              <mesh
                name='bancale_coca_broken_Plastic002_0'
                geometry={nodes.bancale_coca_broken_Plastic002_0.geometry}
                material={materials["Plastic.002"]}
                userData={{ name: "bancale coca broken_Plastic.002_0" }}
              />
              <mesh
                name='bancale_coca_broken_Cocaine_pack001_0'
                geometry={nodes.bancale_coca_broken_Cocaine_pack001_0.geometry}
                material={materials["Cocaine_pack.001"]}
                userData={{ name: "bancale coca broken_Cocaine pack.001_0" }}
              />
              <mesh
                name='bancale_coca_broken_Bancale002_0'
                geometry={nodes.bancale_coca_broken_Bancale002_0.geometry}
                material={materials["Bancale.001"]}
                userData={{ name: "bancale coca broken_Bancale.002_0" }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/cocaine_pack-transformed.glb"
);
