/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Canary Games (https://sketchfab.com/CapAlatriste)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/boo-halloween2019-8a4ed17bb63847069191aa254f3331da
title: Boo! "Halloween2019"
*/

import React, {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
} from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/halloween.glb"
  );
  const instances = useMemo(
    () => ({
      Object: glb.nodes.Object_2,
      Object1: glb.nodes.Object_3,
      Object2: glb.nodes.Object_4,
      Object3: glb.nodes.Object_5,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Halloween(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name='Ghostobjcleanermaterialmergergles'
          userData={{ name: "Ghost.obj.cleaner.materialmerger.gles" }}
        >
          <instances.Object name='Object_2' userData={{ name: "Object_2" }} />
          <instances.Object1 name='Object_3' userData={{ name: "Object_3" }} />
          <instances.Object2 name='Object_4' userData={{ name: "Object_4" }} />
          <instances.Object3 name='Object_5' userData={{ name: "Object_5" }} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(import.meta.env.VITE_ASSETS_PATH + "/models/halloween.glb");
