/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: luarnp (https://sketchfab.com/luarnp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/invisible-queen-a3cbc1f47d09456eaf982a61351adde8
title: Invisible Queen
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Invisible_queen(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/invisible_queen-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Wave 01"].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null} rotation-y={Math.PI / 1}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group name='root' userData={{ name: "root" }}>
            <group
              name='GLTF_SceneRootNode'
              rotation={[Math.PI / 2, 0, 0]}
              userData={{ name: "GLTF_SceneRootNode" }}
            >
              <group
                name='Root-Global_0'
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-1, 1, 1]}
                userData={{ name: "Root-Global_0" }}
              >
                <group
                  name='Controller-Global_2'
                  position={[0, 24, 0]}
                  userData={{ name: "Controller-Global_2" }}
                >
                  <group
                    name='Hip-Global_4'
                    position={[-0.13, 0, -0.29]}
                    rotation={[0, -0.09, -0.01]}
                    userData={{ name: "Hip-Global_4" }}
                  >
                    <group
                      name='Belly-Global_6'
                      position={[0, 2.5, 0]}
                      rotation={[0, 0.03, 0.01]}
                      userData={{ name: "Belly-Global_6" }}
                    >
                      <group
                        name='Belly-Local_7'
                        position={[0, -2, 0]}
                        userData={{ name: "Belly-Local_7" }}
                      >
                        <mesh
                          name='Object_12'
                          geometry={nodes.Object_12.geometry}
                          material={materials["Belly-Material"]}
                          userData={{ name: "Object_12" }}
                        />
                      </group>
                      <group
                        name='Chest-Global_8'
                        position={[0, 4, 0]}
                        rotation={[0, 0.17, -0.03]}
                        userData={{ name: "Chest-Global_8" }}
                      >
                        <group
                          name='Chest-Local_9'
                          position={[0, 7, 0]}
                          userData={{ name: "Chest-Local_9" }}
                        >
                          <mesh
                            name='Object_15'
                            geometry={nodes.Object_15.geometry}
                            material={materials["ChestA-Material"]}
                            userData={{ name: "Object_15" }}
                          />
                        </group>
                        <group
                          name='Head-Global_10'
                          position={[-0.02, 10, 0]}
                          rotation={[0, -0.09, -0.02]}
                          userData={{ name: "Head-Global_10" }}
                        >
                          <group
                            name='Head-Local_11'
                            position={[0, 14.42, 0.76]}
                            userData={{ name: "Head-Local_11" }}
                          >
                            <mesh
                              name='Object_18'
                              geometry={nodes.Object_18.geometry}
                              material={materials["queenhead-Material"]}
                              userData={{ name: "Object_18" }}
                            />
                          </group>
                        </group>
                        <group
                          name='Left_Arm-Global_12'
                          position={[-7, 8, 0]}
                          rotation={[-0.26, 0.04, 1.49]}
                          userData={{ name: "Left_Arm-Global_12" }}
                        >
                          <group
                            name='Left_Arm-Local_13'
                            position={[-4, 1.5, 0]}
                            userData={{ name: "Left_Arm-Local_13" }}
                          >
                            <mesh
                              name='Object_21'
                              geometry={nodes.Object_21.geometry}
                              material={materials["LeftArm-Material"]}
                              userData={{ name: "Object_21" }}
                            />
                          </group>
                          <group
                            name='Left_Forearm-Global_14'
                            position={[-11, 0, -0.5]}
                            rotation={[-0.02, 0.52, 0.09]}
                            userData={{ name: "Left_Forearm-Global_14" }}
                          >
                            <group
                              name='Left_Hand-Global_16'
                              position={[-8, 0, 0]}
                              rotation={[-Math.PI / 2, 0, 0]}
                              userData={{ name: "Left_Hand-Global_16" }}
                            >
                              <group
                                name='Left_Hand-Local_17'
                                position={[-5, 0, -0.5]}
                                userData={{ name: "Left_Hand-Local_17" }}
                              >
                                <mesh
                                  name='Object_27'
                                  geometry={nodes.Object_27.geometry}
                                  material={materials["LeftArm-Material"]}
                                  userData={{ name: "Object_27" }}
                                />
                              </group>
                            </group>
                            <group
                              name='Left_Forearm-Local_15'
                              position={[-4, 0.55, 0.45]}
                              userData={{ name: "Left_Forearm-Local_15" }}
                            >
                              <mesh
                                name='Object_24'
                                geometry={nodes.Object_24.geometry}
                                material={materials["LeftArm-Material"]}
                                userData={{ name: "Object_24" }}
                              />
                            </group>
                          </group>
                        </group>
                        <group
                          name='Right_Arm-Global_18'
                          position={[7, 8, 0]}
                          rotation={[0.43, 0.07, -1.41]}
                          userData={{ name: "Right_Arm-Global_18" }}
                        >
                          <group
                            name='Right_Arm-Local_19'
                            position={[4, 1.5, 0]}
                            userData={{ name: "Right_Arm-Local_19" }}
                          >
                            <mesh
                              name='Object_30'
                              geometry={nodes.Object_30.geometry}
                              material={materials["RightArm-Material"]}
                              userData={{ name: "Object_30" }}
                            />
                          </group>
                          <group
                            name='Right_Forearm-Global_20'
                            position={[11, 0, -0.5]}
                            rotation={[0, -Math.PI / 9, 0]}
                            userData={{ name: "Right_Forearm-Global_20" }}
                          >
                            <group
                              name='Right_Forearm-Local_21'
                              position={[3, 0.56, 0.45]}
                              userData={{ name: "Right_Forearm-Local_21" }}
                            >
                              <mesh
                                name='Object_33'
                                geometry={nodes.Object_33.geometry}
                                material={materials["RightArm-Material"]}
                                userData={{ name: "Object_33" }}
                              />
                            </group>
                            <group
                              name='Right_Hand-Global_22'
                              position={[8, 0, 0]}
                              rotation={[-Math.PI / 2, 0, 0]}
                              userData={{ name: "Right_Hand-Global_22" }}
                            >
                              <group
                                name='Right_Hand-Local_23'
                                position={[5, 0, -0.5]}
                                userData={{ name: "Right_Hand-Local_23" }}
                              >
                                <mesh
                                  name='Object_36'
                                  geometry={nodes.Object_36.geometry}
                                  material={materials["RightArm-Material"]}
                                  userData={{ name: "Object_36" }}
                                />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group
                      name='Right_Thigh-Global_24'
                      position={[4, -0.5, 0]}
                      rotation={[-0.44, 0.07, -0.01]}
                      userData={{ name: "Right_Thigh-Global_24" }}
                    >
                      <group
                        name='Right_Leg-Global_26'
                        position={[0.5, -12, -0.5]}
                        userData={{ name: "Right_Leg-Global_26" }}
                      >
                        <group
                          name='Right_Foot-Global_28'
                          position={[0, -10, 0.5]}
                          rotation={[0, 0.09, 0.04]}
                          userData={{ name: "Right_Foot-Global_28" }}
                        >
                          <group
                            name='Right_Foot-Local_29'
                            position={[0, -0.5, 2]}
                            userData={{ name: "Right_Foot-Local_29" }}
                          >
                            <mesh
                              name='Object_45'
                              geometry={nodes.Object_45.geometry}
                              material={materials["Rightfoot-Material"]}
                              userData={{ name: "Object_45" }}
                            />
                          </group>
                        </group>
                        <group
                          name='Right_Leg-Local_27'
                          position={[-0.5, -5, -0.5]}
                          userData={{ name: "Right_Leg-Local_27" }}
                        >
                          <mesh
                            name='Object_42'
                            geometry={nodes.Object_42.geometry}
                            material={materials["RightLeg-Material"]}
                            userData={{ name: "Object_42" }}
                          />
                        </group>
                      </group>
                      <group
                        name='Right_Thigh-Local_25'
                        position={[-0.05, -6, -0.06]}
                        userData={{ name: "Right_Thigh-Local_25" }}
                      >
                        <mesh
                          name='Object_39'
                          geometry={nodes.Object_39.geometry}
                          material={materials["RightThigh-Material"]}
                          userData={{ name: "Object_39" }}
                        />
                      </group>
                    </group>
                    <group
                      name='Left_Thigh-Global_30'
                      position={[-4, -0.5, 0]}
                      rotation={[0.35, 0, 0.06]}
                      userData={{ name: "Left_Thigh-Global_30" }}
                    >
                      <group
                        name='Left_Leg-Global_32'
                        position={[-0.5, -12, -0.5]}
                        rotation={[0.26, 0, 0]}
                        userData={{ name: "Left_Leg-Global_32" }}
                      >
                        <group
                          name='Left_Foot-Global_34'
                          position={[0, -10, 0.5]}
                          rotation={[-0.26, -0.07, -0.07]}
                          userData={{ name: "Left_Foot-Global_34" }}
                        >
                          <group
                            name='Left_Foot-Local_35'
                            position={[0, -0.5, 2]}
                            userData={{ name: "Left_Foot-Local_35" }}
                          >
                            <mesh
                              name='Object_54'
                              geometry={nodes.Object_54.geometry}
                              material={materials["LeftFoot-Material"]}
                              userData={{ name: "Object_54" }}
                            />
                          </group>
                        </group>
                        <group
                          name='Left_Leg-Local_33'
                          position={[-0.5, -5, -0.5]}
                          userData={{ name: "Left_Leg-Local_33" }}
                        >
                          <mesh
                            name='Object_51'
                            geometry={nodes.Object_51.geometry}
                            material={materials["RightLeg-Material"]}
                            userData={{ name: "Object_51" }}
                          />
                        </group>
                      </group>
                      <group
                        name='Left_Thigh-Local_31'
                        position={[0.05, -6, -0.05]}
                        userData={{ name: "Left_Thigh-Local_31" }}
                      >
                        <mesh
                          name='Object_48'
                          geometry={nodes.Object_48.geometry}
                          material={materials["RightThigh-Material"]}
                          userData={{ name: "Object_48" }}
                        />
                      </group>
                    </group>
                    <group
                      name='Hip-Local_5'
                      position={[0, 0.5, 0]}
                      userData={{ name: "Hip-Local_5" }}
                    >
                      <mesh
                        name='Object_9'
                        geometry={nodes.Object_9.geometry}
                        material={materials["Hip-Material"]}
                        userData={{ name: "Object_9" }}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/invisible_queen-transformed.glb"
);
