/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useMemo, useContext, createContext, useEffect } from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/mannequin.glb"
  );

  const instances = useMemo(
    () => ({
      Shirtmannequin: glb.nodes.shirt_mannequin_1,
      Mannequinpants: glb.nodes.mannequin_pants_1,
      Mannequinbody: glb.nodes.mannequin_body_1,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged scale={[0.23, 0.23, 0.23]} meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Mannequin(props) {
  const instances = useContext(context);

  return (
    <group {...props} dispose={null}>
      <group
        name='Mannequin_forSubstanceobj'
        userData={{ name: "Mannequin_forSubstance.obj" }}
      >
        <group name='shirt_mannequin' userData={{ name: "shirt mannequin" }}>
          <instances.Shirtmannequin
            name='shirt_mannequin_1'
            userData={{ name: "shirt mannequin" }}
          />
        </group>
        <group name='mannequin_pants' userData={{ name: "mannequin pants" }}>
          <instances.Mannequinpants
            name='mannequin_pants_1'
            userData={{ name: "mannequin pants" }}
          />
        </group>
        <group name='mannequin_body' userData={{ name: "mannequin body" }}>
          <instances.Mannequinbody
            name='mannequin_body_1'
            userData={{ name: "mannequin body" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(import.meta.env.VITE_ASSETS_PATH + "/models/mannequin.glb");
