/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.VITE_ASSETS_PATH +
      "/humanityRocks/models/purple_shuttle-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group>
        <group
          name='Group001'
          position={[0.01, 0, 0.03]}
          userData={{ name: "Group001" }}
        >
          <mesh
            name='Stryker_final_StrykerSkate_boardskate_ctrlp2_non_organic'
            geometry={
              nodes.Stryker_final_StrykerSkate_boardskate_ctrlp2_non_organic
                .geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "Stryker_final_StrykerSkate_boardskate_ctrlp2_non_organic",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerearringsearing7'
            geometry={
              nodes.non_organic_Stryker_final_Strykerearringsearing7.geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_Strykerearringsearing7",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerearringsearring12'
            geometry={
              nodes.non_organic_Stryker_final_Strykerearringsearring12.geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_Strykerearringsearring12",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerearringsearring13'
            geometry={
              nodes.non_organic_Stryker_final_Strykerearringsearring13.geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_Strykerearringsearring13",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerearringsearring14'
            geometry={
              nodes.non_organic_Stryker_final_Strykerearringsearring14.geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_Strykerearringsearring14",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerpants'
            geometry={nodes.non_organic_Stryker_final_Strykerpants.geometry}
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "non_organic_Stryker_final_Strykerpants" }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykershirt'
            geometry={nodes.non_organic_Stryker_final_Strykershirt.geometry}
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "non_organic_Stryker_final_Strykershirt" }}
          />
          <mesh
            name='non_organic_Stryker_final_StrykerSkate_boardSkate_board'
            geometry={
              nodes.non_organic_Stryker_final_StrykerSkate_boardSkate_board
                .geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_StrykerSkate_boardSkate_board",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_StrykerSkate_boardSkate_board_front'
            geometry={
              nodes
                .non_organic_Stryker_final_StrykerSkate_boardSkate_board_front
                .geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_StrykerSkate_boardSkate_board_front",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_StrykerSkate_boardSkate_nail11'
            geometry={
              nodes.non_organic_Stryker_final_StrykerSkate_boardSkate_nail11
                .geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_StrykerSkate_boardSkate_nail11",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_StrykerSkate_boardwheel5'
            geometry={
              nodes.non_organic_Stryker_final_StrykerSkate_boardwheel5.geometry
            }
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{
              name: "non_organic_Stryker_final_StrykerSkate_boardwheel5",
            }}
          />
          <mesh
            name='non_organic_Stryker_final_Strykerwatch'
            geometry={nodes.non_organic_Stryker_final_Strykerwatch.geometry}
            material={materials.non_organic_MAT}
            position={[-0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "non_organic_Stryker_final_Strykerwatch" }}
          />
        </group>
        <group
          name='Group002'
          position={[-0.01, -0.01, 0.02]}
          userData={{ name: "Group002" }}
        >
          <mesh
            name='organic_Stryker_final_HairStryker'
            geometry={nodes.organic_Stryker_final_HairStryker.geometry}
            material={materials.organic_MAT}
            position={[0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "organic_Stryker_final_HairStryker" }}
          />
          <mesh
            name='organic_Stryker_final_StrykereyebrowFace'
            geometry={nodes.organic_Stryker_final_StrykereyebrowFace.geometry}
            material={materials.organic_MAT}
            position={[0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "organic_Stryker_final_StrykereyebrowFace" }}
          />
          <mesh
            name='organic_Stryker_final_StrykerFaceface2'
            geometry={nodes.organic_Stryker_final_StrykerFaceface2.geometry}
            material={materials.organic_MAT}
            position={[0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "organic_Stryker_final_StrykerFaceface2" }}
          />
          <mesh
            name='organic_Stryker_final_StrykerFacetooth'
            geometry={nodes.organic_Stryker_final_StrykerFacetooth.geometry}
            material={materials.organic_MAT}
            position={[0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "organic_Stryker_final_StrykerFacetooth" }}
          />
          <mesh
            name='Stryker_final_StrykerFaceeyeball2_organic'
            geometry={nodes.Stryker_final_StrykerFaceeyeball2_organic.geometry}
            material={materials.organic_MAT}
            position={[0.01, -0.1, 0.02]}
            rotation={[-0.27, 0, 0]}
            userData={{ name: "Stryker_final_StrykerFaceeyeball2_organic" }}
          />
        </group>
        <group
          name='Group003'
          position={[0, -0.05, 0.09]}
          userData={{ name: "Group003" }}
        >
          <mesh
            name='group1_logo_forSubstance2_a'
            geometry={nodes.group1_logo_forSubstance2_a.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_a" }}
          />
          <mesh
            name='group1_logo_forSubstance2_c'
            geometry={nodes.group1_logo_forSubstance2_c.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_c" }}
          />
          <mesh
            name='group1_logo_forSubstance2_dash'
            geometry={nodes.group1_logo_forSubstance2_dash.geometry}
            material={materials.logo_forSubstance2_Material_001}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_dash" }}
          />
          <mesh
            name='group1_logo_forSubstance2_earth'
            geometry={nodes.group1_logo_forSubstance2_earth.geometry}
            material={materials.logo_forSubstance2_DefaultMaterial_001}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_earth" }}
          />
          <mesh
            name='group1_logo_forSubstance2_face1'
            geometry={nodes.group1_logo_forSubstance2_face1.geometry}
            material={materials.logo_forSubstance2_standardSurface1SG}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_face1" }}
          />
          <mesh
            name='group1_logo_forSubstance2_face2'
            geometry={nodes.group1_logo_forSubstance2_face2.geometry}
            material={materials.logo_forSubstance2_standardSurface1SG}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_face2" }}
          />
          <mesh
            name='group1_logo_forSubstance2_face3'
            geometry={nodes.group1_logo_forSubstance2_face3.geometry}
            material={materials.logo_forSubstance2_standardSurface1SG}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_face3" }}
          />
          <mesh
            name='group1_logo_forSubstance2_face3_ring'
            geometry={nodes.group1_logo_forSubstance2_face3_ring.geometry}
            material={materials.logo_forSubstance2_standardSurface1SG}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_face3_ring" }}
          />
          <mesh
            name='group1_logo_forSubstance2_h'
            geometry={nodes.group1_logo_forSubstance2_h.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_h" }}
          />
          <mesh
            name='group1_logo_forSubstance2_i'
            geometry={nodes.group1_logo_forSubstance2_i.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_i" }}
          />
          <mesh
            name='group1_logo_forSubstance2_k'
            geometry={nodes.group1_logo_forSubstance2_k.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_k" }}
          />
          <mesh
            name='group1_logo_forSubstance2_Mesh'
            geometry={nodes.group1_logo_forSubstance2_Mesh.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_Mesh" }}
          />
          <mesh
            name='group1_logo_forSubstance2_MeshpolySurface20'
            geometry={
              nodes.group1_logo_forSubstance2_MeshpolySurface20.geometry
            }
            material={materials.logo_forSubstance2_Material_001}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_MeshpolySurface20" }}
          />
          <mesh
            name='group1_logo_forSubstance2_MeshpolySurface21'
            geometry={
              nodes.group1_logo_forSubstance2_MeshpolySurface21.geometry
            }
            material={materials.logo_forSubstance2_Material_001}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_MeshpolySurface21" }}
          />
          <mesh
            name='group1_logo_forSubstance2_r'
            geometry={nodes.group1_logo_forSubstance2_r.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_r" }}
          />
          <mesh
            name='group1_logo_forSubstance2_s'
            geometry={nodes.group1_logo_forSubstance2_s.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_s" }}
          />
          <mesh
            name='group1_logo_forSubstance2_t'
            geometry={nodes.group1_logo_forSubstance2_t.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_t" }}
          />
          <mesh
            name='group1_logo_forSubstance2_u'
            geometry={nodes.group1_logo_forSubstance2_u.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_u" }}
          />
          <mesh
            name='group1_logo_forSubstance2_y'
            geometry={nodes.group1_logo_forSubstance2_y.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "group1_logo_forSubstance2_y" }}
          />
          <mesh
            name='logo_forSubstance2_n_group1'
            geometry={nodes.logo_forSubstance2_n_group1.geometry}
            material={materials.logo_forSubstance2_Default_OBJ}
            position={[0, 0.05, -0.09]}
            userData={{ name: "logo_forSubstance2_n_group1" }}
          />
        </group>
        <mesh
          name='metal_hp'
          geometry={nodes.metal_hp.geometry}
          material={materials.non_rock_purple_MAT}
          userData={{ name: "metal_hp" }}
        />
        <mesh
          name='seat_RetroSeat'
          geometry={nodes.seat_RetroSeat.geometry}
          material={materials.non_rock_purple_MAT}
          userData={{ name: "seat_RetroSeat" }}
        />
        <mesh
          name='rock1'
          geometry={nodes.rock1.geometry}
          material={materials.rock_purple_MAT}
          userData={{ name: "rock1" }}
        />
        <mesh
          name='glass_hp'
          geometry={nodes.glass_hp.geometry}
          material={materials.glass_MAT}
          userData={{ name: "glass_hp" }}
        />
        <mesh
          name='polySurface1_inner_wall'
          geometry={nodes.polySurface1_inner_wall.geometry}
          material={materials.non_rock_purple_MAT}
          userData={{ name: "polySurface1_inner_wall" }}
        />
        <mesh
          name='inner_wall_polySurface2'
          geometry={nodes.inner_wall_polySurface2.geometry}
          material={materials.panel_MAT}
          userData={{ name: "inner_wall_polySurface2" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH +
    "/humanityRocks/models//purple_shuttle-transformed.glb"
);
