/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: romullus (https://sketchfab.com/romullus)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/rubiks-cube-speed-solving-7472d2f875fc43bd9ddac4a611cd80ce
title: Rubik's Cube Speed Solving
*/

import React, {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
} from "react";
import { useGLTF, Merged, useAnimations } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/rubiks_cube_speed_solving.glb"
  );
  const instances = useMemo(
    () => ({
      RCenterRubik: glb.nodes.R2Center_01_Rubik_0,
      RCenterRubik1: glb.nodes.R2Center_02_Rubik_0,
      RCenterRubik2: glb.nodes.R2Center_03_Rubik_0,
      RCenterRubik3: glb.nodes.R2Center_04_Rubik_0,
      RCornerRubik: glb.nodes.R2Corner_01_Rubik_0,
      RCornerRubik1: glb.nodes.R2Corner_02_Rubik_0,
      RCornerRubik2: glb.nodes.R2Corner_03_Rubik_0,
      RCornerRubik3: glb.nodes.R2Corner_04_Rubik_0,
      RCornerRubik4: glb.nodes.R2Corner_05_Rubik_0,
      RCornerRubik5: glb.nodes.R2Corner_06_Rubik_0,
      RCornerRubik6: glb.nodes.R2Corner_07_Rubik_0,
      RCornerRubik7: glb.nodes.R2Corner_08_Rubik_0,
      REdgeRubik: glb.nodes.R2Edge_01_Rubik_0,
      REdgeRubik1: glb.nodes.R2Edge_02_Rubik_0,
      REdgeRubik2: glb.nodes.R2Edge_03_Rubik_0,
      REdgeRubik3: glb.nodes.R2Edge_04_Rubik_0,
      REdgeRubik4: glb.nodes.R2Edge_05_Rubik_0,
      REdgeRubik5: glb.nodes.R2Edge_06_Rubik_0,
      REdgeRubik6: glb.nodes.R2Edge_07_Rubik_0,
      REdgeRubik7: glb.nodes.R2Edge_08_Rubik_0,
      REdgeRubik8: glb.nodes.R2Edge_09_Rubik_0,
      REdgeRubik9: glb.nodes.R2Edge_010_Rubik_0,
      REdgeRubik10: glb.nodes.R2Edge_012_Rubik_0,
      RCenterRubik4: glb.nodes.R2Center_05_Rubik_0,
      RCenterRubik5: glb.nodes.R2Center_06_Rubik_0,
      REdgeRubik11: glb.nodes.R2Edge_011_Rubik_0,
      RCoreRubik: glb.nodes.R2Core_Rubik_0,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    glb.scene.traverse((child) => {
      child.castShadow = true;
    });

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function RubiksCube(props) {
  const instances = useContext(context);
  const group = useRef();
  // const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' userData={{ name: "Sketchfab_model" }}>
          <group
            name='423b0ad940a347de9094c47481f985befbx'
            rotation={[-Math.PI, 0, 0]}
            userData={{ name: "423b0ad940a347de9094c47481f985be.fbx" }}
          >
            <group name='Object_2' userData={{ name: "Object_2" }}>
              <group name='RootNode' userData={{ name: "RootNode" }}>
                <group name='Rig_Main' userData={{ name: "Rig_Main" }}>
                  <group name='Rig_LR' userData={{ name: "Rig_LR" }} />
                  <group name='Rig_UD' userData={{ name: "Rig_UD" }} />
                  <group name='Rig_FB' userData={{ name: "Rig_FB" }} />
                  <group
                    name='R2Core'
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    userData={{ name: "R2.Core" }}
                  >
                    <group
                      name='R2Center_01'
                      rotation={[-Math.PI, 0, -Math.PI]}
                      userData={{ name: "R2.Center_01" }}
                    >
                      <group
                        name='Object_11'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_11" }}
                      >
                        <instances.RCenterRubik
                          name='R2Center_01_Rubik_0'
                          userData={{ name: "R2.Center_01_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Center_02'
                      rotation={[0, -1.57, 0]}
                      userData={{ name: "R2.Center_02" }}
                    >
                      <group
                        name='Object_14'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_14" }}
                      >
                        <instances.RCenterRubik1
                          name='R2Center_02_Rubik_0'
                          userData={{ name: "R2.Center_02_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Center_03'
                      rotation={[Math.PI / 2, 0, 0]}
                      userData={{ name: "R2.Center_03" }}
                    >
                      <group
                        name='Object_17'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_17" }}
                      >
                        <instances.RCenterRubik2
                          name='R2Center_03_Rubik_0'
                          userData={{ name: "R2.Center_03_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Center_04'
                      rotation={[0, 0, Math.PI]}
                      userData={{ name: "R2.Center_04" }}
                    >
                      <group
                        name='Object_20'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_20" }}
                      >
                        <instances.RCenterRubik3
                          name='R2Center_04_Rubik_0'
                          userData={{ name: "R2.Center_04_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_01'
                      rotation={[0, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Corner_01" }}
                    >
                      <group
                        name='Object_29'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_29" }}
                      >
                        <instances.RCornerRubik
                          name='R2Corner_01_Rubik_0'
                          userData={{ name: "R2.Corner_01_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_02'
                      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                      userData={{ name: "R2.Corner_02" }}
                    >
                      <group
                        name='Object_32'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_32" }}
                      >
                        <instances.RCornerRubik1
                          name='R2Corner_02_Rubik_0'
                          userData={{ name: "R2.Corner_02_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_03'
                      rotation={[0, 0, -Math.PI / 2]}
                      userData={{ name: "R2.Corner_03" }}
                    >
                      <group
                        name='Object_35'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_35" }}
                      >
                        <instances.RCornerRubik2
                          name='R2Corner_03_Rubik_0'
                          userData={{ name: "R2.Corner_03_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_04'
                      rotation={[Math.PI, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Corner_04" }}
                    >
                      <group
                        name='Object_38'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_38" }}
                      >
                        <instances.RCornerRubik3
                          name='R2Corner_04_Rubik_0'
                          userData={{ name: "R2.Corner_04_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_05'
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                      userData={{ name: "R2.Corner_05" }}
                    >
                      <group
                        name='Object_41'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_41" }}
                      >
                        <instances.RCornerRubik4
                          name='R2Corner_05_Rubik_0'
                          userData={{ name: "R2.Corner_05_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_06'
                      rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                      userData={{ name: "R2.Corner_06" }}
                    >
                      <group
                        name='Object_44'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_44" }}
                      >
                        <instances.RCornerRubik5
                          name='R2Corner_06_Rubik_0'
                          userData={{ name: "R2.Corner_06_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_07'
                      rotation={[0, 0, -Math.PI / 2]}
                      userData={{ name: "R2.Corner_07" }}
                    >
                      <group
                        name='Object_47'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_47" }}
                      >
                        <instances.RCornerRubik6
                          name='R2Corner_07_Rubik_0'
                          userData={{ name: "R2.Corner_07_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Corner_08'
                      rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Corner_08" }}
                    >
                      <group
                        name='Object_50'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_50" }}
                      >
                        <instances.RCornerRubik7
                          name='R2Corner_08_Rubik_0'
                          userData={{ name: "R2.Corner_08_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_01'
                      rotation={[Math.PI, 0, Math.PI]}
                      userData={{ name: "R2.Edge_01" }}
                    >
                      <group
                        name='Object_53'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_53" }}
                      >
                        <instances.REdgeRubik
                          name='R2Edge_01_Rubik_0'
                          userData={{ name: "R2.Edge_01_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_02'
                      rotation={[-Math.PI / 2, 0, 0]}
                      userData={{ name: "R2.Edge_02" }}
                    >
                      <group
                        name='Object_56'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_56" }}
                      >
                        <instances.REdgeRubik1
                          name='R2Edge_02_Rubik_0'
                          userData={{ name: "R2.Edge_02_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_03'
                      rotation={[0, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Edge_03" }}
                    >
                      <group
                        name='Object_59'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_59" }}
                      >
                        <instances.REdgeRubik2
                          name='R2Edge_03_Rubik_0'
                          userData={{ name: "R2.Edge_03_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_04'
                      rotation={[0, 0, -Math.PI / 2]}
                      userData={{ name: "R2.Edge_04" }}
                    >
                      <group
                        name='Object_62'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_62" }}
                      >
                        <instances.REdgeRubik3
                          name='R2Edge_04_Rubik_0'
                          userData={{ name: "R2.Edge_04_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group name='R2Edge_05' userData={{ name: "R2.Edge_05" }}>
                      <group
                        name='Object_65'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_65" }}
                      >
                        <instances.REdgeRubik4
                          name='R2Edge_05_Rubik_0'
                          userData={{ name: "R2.Edge_05_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_06'
                      rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Edge_06" }}
                    >
                      <group
                        name='Object_68'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_68" }}
                      >
                        <instances.REdgeRubik5
                          name='R2Edge_06_Rubik_0'
                          userData={{ name: "R2.Edge_06_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_07'
                      rotation={[Math.PI / 2, 1.57, 0]}
                      userData={{ name: "R2.Edge_07" }}
                    >
                      <group
                        name='Object_71'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_71" }}
                      >
                        <instances.REdgeRubik6
                          name='R2Edge_07_Rubik_0'
                          userData={{ name: "R2.Edge_07_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_08'
                      rotation={[Math.PI, -Math.PI / 2, 0]}
                      userData={{ name: "R2.Edge_08" }}
                    >
                      <group
                        name='Object_74'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_74" }}
                      >
                        <instances.REdgeRubik7
                          name='R2Edge_08_Rubik_0'
                          userData={{ name: "R2.Edge_08_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_09'
                      rotation={[0, -1.57, 0]}
                      userData={{ name: "R2.Edge_09" }}
                    >
                      <group
                        name='Object_77'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_77" }}
                      >
                        <instances.REdgeRubik8
                          name='R2Edge_09_Rubik_0'
                          userData={{ name: "R2.Edge_09_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_010'
                      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                      userData={{ name: "R2.Edge_010" }}
                    >
                      <group
                        name='Object_80'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_80" }}
                      >
                        <instances.REdgeRubik9
                          name='R2Edge_010_Rubik_0'
                          userData={{ name: "R2.Edge_010_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Edge_012'
                      rotation={[Math.PI / 2, 0, -Math.PI]}
                      userData={{ name: "R2.Edge_012" }}
                    >
                      <group
                        name='Object_86'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_86" }}
                      >
                        <instances.REdgeRubik10
                          name='R2Edge_012_Rubik_0'
                          userData={{ name: "R2.Edge_012_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Center_05'
                      userData={{ name: "R2.Center_05" }}
                    >
                      <group
                        name='Object_23'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_23" }}
                      >
                        <instances.RCenterRubik4
                          name='R2Center_05_Rubik_0'
                          userData={{ name: "R2.Center_05_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group
                      name='R2Center_06'
                      rotation={[0, 0, -Math.PI]}
                      userData={{ name: "R2.Center_06" }}
                    >
                      <group
                        name='Object_26'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_26" }}
                      >
                        <instances.RCenterRubik5
                          name='R2Center_06_Rubik_0'
                          userData={{ name: "R2.Center_06_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <group name='R2Edge_011' userData={{ name: "R2.Edge_011" }}>
                      <group
                        name='Object_83'
                        position={[0, -1.87, 0]}
                        userData={{ name: "Object_83" }}
                      >
                        <instances.REdgeRubik11
                          name='R2Edge_011_Rubik_0'
                          userData={{ name: "R2.Edge_011_Rubik_0" }}
                        />
                      </group>
                    </group>
                    <instances.RCoreRubik
                      name='R2Core_Rubik_0'
                      userData={{ name: "R2.Core_Rubik_0" }}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/rubiks_cube_speed_solving.glb"
);
