/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: VRA (https://sketchfab.com/architect47)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gallery-05m-baked-8efa3757a0924302881c0b9ba8583e63
title: Gallery 05M Baked
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Scene(props) {
  const { nodes, materials } = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "models/scene-transformed.glb"
  );
  return (
    <group scale={0.01125} {...props} dispose={null}>
      <group
        name='Sketchfab_model'
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "Sketchfab_model" }}
      >
        <group
          name='62c2049eda30405aaac899129179e275fbx'
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: "62c2049eda30405aaac899129179e275.fbx" }}
        >
          <group name='RootNode' userData={{ name: "RootNode" }}>
            <group
              name='a15'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a15" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a15_CRNa15_0'
                geometry={nodes.a15_CRNa15_0.geometry}
                material={materials["CRN.a15"]}
                userData={{ name: "a15_CRN.a15_0" }}
              />
            </group>
            <group
              name='base'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "base" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='base_Stucco_White2_0'
                geometry={nodes.base_Stucco_White2_0.geometry}
                material={materials.Stucco_White2}
                userData={{ name: "base_Stucco White2_0" }}
              />
            </group>
            <group
              name='a2'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a2" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a2_CRNa2_0'
                geometry={nodes.a2_CRNa2_0.geometry}
                material={materials["CRN.a2"]}
                userData={{ name: "a2_CRN.a2_0" }}
              />
            </group>
            <group
              name='a17'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a17" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a17_CRNa17_0'
                geometry={nodes.a17_CRNa17_0.geometry}
                material={materials["CRN.a17"]}
                userData={{ name: "a17_CRN.a17_0" }}
              />
            </group>
            <group
              name='a12'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a12" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a12_CRNa12_0'
                geometry={nodes.a12_CRNa12_0.geometry}
                material={materials["CRN.a12"]}
                userData={{ name: "a12_CRN.a12_0" }}
              />
            </group>
            <group
              name='Arch'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Arch" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Arch_Stucco_White3_0'
                geometry={nodes.Arch_Stucco_White3_0.geometry}
                material={materials.Stucco_White3}
                userData={{ name: "Arch_Stucco White3_0" }}
              />
            </group>
            <group
              name='Soil'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Soil" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Soil_CRN����������_-_��������������������_0'
                geometry={
                  nodes["Soil_CRN����������_-_��������������������_0"].geometry
                }
                material={materials["CRN._-"]}
                userData={{
                  name: "Soil_CRN.���������� - ��������������������_0",
                }}
              />
            </group>
            <group
              name='a20'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a20" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a20_CRNa20_0'
                geometry={nodes.a20_CRNa20_0.geometry}
                material={materials["CRN.a20"]}
                userData={{ name: "a20_CRN.a20_0" }}
              />
            </group>
            <group
              name='Wall_01'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Wall_01" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Wall_01_Stucco_White_0'
                geometry={nodes.Wall_01_Stucco_White_0.geometry}
                material={materials.Stucco_White}
                userData={{ name: "Wall_01_Stucco White_0" }}
              />
            </group>
            <group
              name='a13'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a13" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a13_CRNa13_0'
                geometry={nodes.a13_CRNa13_0.geometry}
                material={materials["CRN.a13"]}
                userData={{ name: "a13_CRN.a13_0" }}
              />
            </group>
            <group
              name='Floor'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Floor" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Floor_CRN������������_-_����������-��������������������_30x30_0'
                geometry={
                  nodes[
                    "Floor_CRN������������_-_����������-��������������������_30x30_0"
                  ].geometry
                }
                material={materials["CRN._-_-_30x30"]}
                userData={{
                  name: "Floor_CRN.������������ - ����������-�������������������� 30x30_0",
                }}
              />
            </group>
            <group
              name='door_frame'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "door_frame" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='door_frame_CRN������������_-_����������_��������������������_����������������������������_0'
                geometry={
                  nodes[
                    "door_frame_CRN������������_-_����������_��������������������_����������������������������_0"
                  ].geometry
                }
                material={materials["CRN._-_11"]}
                userData={{
                  name: "door_frame_CRN.������������ - ���������� �������������������� ����������������������������_0",
                }}
              />
            </group>
            <group
              name='��_AT3_Bark_001'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "�� AT3_Bark_001" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='��_AT3_Bark_001_CRN��_AT3_Bark_001_0'
                geometry={
                  nodes["��_AT3_Bark_001_CRN��_AT3_Bark_001_0"].geometry
                }
                material={materials["CRN._AT3_Bark_001"]}
                userData={{ name: "�� AT3_Bark_001_CRN.�� AT3_Bark_001_0" }}
              />
            </group>
            <group
              name='Roof'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Roof" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Roof_Stucco_White0_0'
                geometry={nodes.Roof_Stucco_White0_0.geometry}
                material={materials.Stucco_White0}
                userData={{ name: "Roof_Stucco White0_0" }}
              />
            </group>
            <group
              name='a14'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a14" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a14_CRNa14_0'
                geometry={nodes.a14_CRNa14_0.geometry}
                material={materials["CRN.a14"]}
                userData={{ name: "a14_CRN.a14_0" }}
              />
            </group>
            <group
              name='Up_column'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Up_column" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Up_column_Stucco_White1_0'
                geometry={nodes.Up_column_Stucco_White1_0.geometry}
                material={materials.Stucco_White1}
                userData={{ name: "Up_column_Stucco White1_0" }}
              />
            </group>
            <group
              name='������������_-_��������������������_��������������'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{
                name: "������������ - �������������������� ��������������",
              }}
            >
              <mesh
                castShadow
                recieveShadow
                name='������������_-_��������������������_��������������_CRN������������_-_��������������������_��������������_0'
                geometry={
                  nodes[
                    "������������_-_��������������������_��������������_CRN������������_-_��������������������_��������������_0"
                  ].geometry
                }
                material={materials["CRN._-_16"]}
                userData={{
                  name: "������������ - �������������������� ��������������_CRN.������������ - �������������������� ��������������_0",
                }}
              />
            </group>
            <group
              name='GDLM32_Mat_1'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "GDLM32_Mat_1" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='GDLM32_Mat_1_Leaf_Cherry_0'
                geometry={nodes.GDLM32_Mat_1_Leaf_Cherry_0.geometry}
                material={materials.Leaf_Cherry}
                userData={{ name: "GDLM32_Mat_1_Leaf Cherry_0" }}
              />
            </group>
            <group
              name='Door'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Door" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Door_CRN����������_-_03_0'
                geometry={nodes["Door_CRN����������_-_03_0"].geometry}
                material={materials["CRN._-_03"]}
                userData={{ name: "Door_CRN.���������� - 03_0" }}
              />
            </group>
            <group
              name='a19'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a19" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a19_CRNa19_0'
                geometry={nodes.a19_CRNa19_0.geometry}
                material={materials["CRN.a19"]}
                userData={{ name: "a19_CRN.a19_0" }}
              />
            </group>
            <group
              name='Mosaic'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Mosaic" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Mosaic_CRN��������������_����������_-_01_0'
                geometry={
                  nodes["Mosaic_CRN��������������_����������_-_01_0"].geometry
                }
                material={materials["CRN.__-_01"]}
                userData={{
                  name: "Mosaic_CRN.�������������� ���������� - 01_0",
                }}
              />
            </group>
            <group
              name='����������_-_02'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "���������� - 02" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='����������_-_02_CRN����������_-_02_0'
                geometry={
                  nodes["����������_-_02_CRN����������_-_02_0"].geometry
                }
                material={materials["CRN._-_02"]}
                userData={{ name: "���������� - 02_CRN.���������� - 02_0" }}
              />
            </group>
            <group
              name='Top_line00'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Top_line00" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Top_line00_Stucco_White6_0'
                geometry={nodes.Top_line00_Stucco_White6_0.geometry}
                material={materials.Stucco_White6}
                userData={{ name: "Top_line00_Stucco White6_0" }}
              />
            </group>
            <group
              name='Column_row'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Column_row" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Column_row_Stucco_White4_0'
                geometry={nodes.Column_row_Stucco_White4_0.geometry}
                material={materials.Stucco_White4}
                userData={{ name: "Column_row_Stucco White4_0" }}
              />
              <mesh
                castShadow
                recieveShadow
                name='Column_row_Stucco_White4_0_1'
                geometry={nodes.Column_row_Stucco_White4_0_1.geometry}
                material={materials.Stucco_White4}
                userData={{ name: "Column_row_Stucco White4_0" }}
              />
            </group>
            <group
              name='a18'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a18" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a18_CRNa18_0'
                geometry={nodes.a18_CRNa18_0.geometry}
                material={materials["CRN.a18"]}
                userData={{ name: "a18_CRN.a18_0" }}
              />
            </group>
            <group
              name='Soil_frame'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Soil_frame" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Soil_frame_CRN����������_-_04_0'
                geometry={nodes["Soil_frame_CRN����������_-_04_0"].geometry}
                material={materials["CRN._-_04"]}
                userData={{ name: "Soil_frame_CRN.���������� - 04_0" }}
              />
            </group>
            <group
              name='������������_-_��������������'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "������������ - ��������������" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='������������_-_��������������_CRN������������_-_��������������_0'
                geometry={
                  nodes[
                    "������������_-_��������������_CRN������������_-_��������������_0"
                  ].geometry
                }
                material={materials["CRN._-_26"]}
                userData={{
                  name: "������������ - ��������������_CRN.������������ - ��������������_0",
                }}
              />
            </group>
            <group
              name='Column_wall'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "Column_wall" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='Column_wall_Stucco_White5_0'
                geometry={nodes.Column_wall_Stucco_White5_0.geometry}
                material={materials.Stucco_White5}
                userData={{ name: "Column_wall_Stucco White5_0" }}
              />
            </group>
            <group
              name='������������_-_����������������'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "������������ - ����������������" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='������������_-_����������������_CRN������������_-_����������������_0'
                geometry={
                  nodes[
                    "������������_-_����������������_CRN������������_-_����������������_0"
                  ].geometry
                }
                material={materials["CRN._-_16"]}
                userData={{
                  name: "������������ - ����������������_CRN.������������ - ����������������_0",
                }}
              />
            </group>
            <group
              name='a16'
              position={[0, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={10}
              userData={{ name: "a16" }}
            >
              <mesh
                castShadow
                recieveShadow
                name='a16_CRNa16_0'
                geometry={nodes.a16_CRNa16_0.geometry}
                material={materials["CRN.a16"]}
                userData={{ name: "a16_CRN.a16_0" }}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "models/scene-transformed.glb"
);
