/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: jonathanborges3d (https://sketchfab.com/jonathanborges3d)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/solar-system-animation-fb26b621efeb4677bd807e0fd7cd8d29
title: Solar System Animation
*/

import React, {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
} from "react";
import { useGLTF, Merged, useAnimations } from "@react-three/drei";
import { useCreatorStore } from "../../hooks/use-creator-store.hook";

const context = createContext();
export function Instances({ children, ...props }) {
  const glb = useGLTF(
    import.meta.env.VITE_ASSETS_PATH + "/models/solar_system_animation.glb"
  );
  const instances = useMemo(
    () => ({
      Object: glb.nodes.Object_8,
      Object1: glb.nodes.Object_13,
      Object2: glb.nodes.Object_18,
      Object3: glb.nodes.Object_23,
      Object4: glb.nodes.Object_28,
      Object5: glb.nodes.Object_35,
      Object6: glb.nodes.Object_36,
      PlanetarioLUNALUNA: glb.nodes.planetarioLUNA_LUNA_0,
      Object7: glb.nodes.Object_41,
      Object8: glb.nodes.Object_49,
      Object9: glb.nodes.Object_55,
      Planetariopolymsharos: glb.nodes.planetariopolymsh_aros_0,
      Planetariosolspheresol: glb.nodes.planetariosolsphere_sol_1_0,
      Planetariosolspheresol1: glb.nodes.planetariosolsphere1_sol_2_0,
      Planetariosolspheresol2: glb.nodes.planetariosolsphere2_sol_1_0,
      Planetariosolspheresol3: glb.nodes.planetariosolsphere3_sol_2_0,
      Planetariosolspheresol4: glb.nodes.planetariosolsphere4_sol_1_0,
      Planetariosolpolymshdetachedcorona:
        glb.nodes.planetariosolpolymsh_detached_corona1_0,
      Planetariosolpolymshdetachedcorona1:
        glb.nodes.planetariosolpolymsh_detached1_corona1_0,
      Planetariosolpolymshdetachedcorona2:
        glb.nodes.planetariosolpolymsh_detached2_corona1_0,
      Planetariosolpolymshdetachedcorona3:
        glb.nodes.planetariosolpolymsh_detached3_corona1_0,
      Planetariosolnucleonucleo: glb.nodes.planetariosolnucleo1_nucleo_1_0,
      PlanetariosolnucleoMaterial: glb.nodes.planetariosolnucleo2_Material_0,
      Planetariosolnucleonucleo1: glb.nodes.planetariosolnucleo3_nucleo_1_0,
      PlanetariosolnucleoMaterial1: glb.nodes.planetariosolnucleo4_Material_0,
      Planetariosolllamaradallamarada:
        glb.nodes.planetariosolllamarada_1_llamarada_1_0,
      Planetariosolllamaradallamarada1:
        glb.nodes.planetariosolllamarada_2_llamarada_1_0,
      Planetariosolllamaradallamarada2:
        glb.nodes.planetariosolllamarada_3_llamarada_1_0,
      Planetariosolllamaradallamarada3:
        glb.nodes.planetariosolllamarada_4_llamarada_1_0,
      PlanetariosolpolymshdetachedSuperfie:
        glb.nodes.planetariosolpolymsh_detached4_Superfie_0,
      PlanetariosolpolymshdetachedSuperfie1:
        glb.nodes.planetariosolpolymsh_detached5_Superfie_0,
      PlanetariosolpolymshdetachedSuperfie2:
        glb.nodes.planetariosolpolymsh_detached6_Superfie_0,
      PlanetariosolpolymshdetachedSuperfie3:
        glb.nodes.planetariosolpolymsh_detached7_Superfie_0,
      Planetariosolspheresol5: glb.nodes.planetariosolsphere5_sol_1_0,
      Planetariosolnucleoamarillo: glb.nodes.planetariosolnucleo_amarillo_0,
    }),
    [glb.nodes]
  );

  const { setModel, model, currentProject } = useCreatorStore();

  useEffect(() => {
    for (const material in model.materialColors) {
      const { color } = model.materialColors[material];

      glb.materials[material].color.set(color);
    }

    glb.scene.traverse((child) => {
      child.castShadow = true;
    });

    setModel({ glb });
  }, [currentProject]);

  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function SolarSystem(props) {
  const instances = useContext(context);
  const group = useRef();
  // const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1}
          position={[0, -1, 0]}
          userData={{ name: "Sketchfab_model" }}
        >
          <group
            name='4db8d02bfff84b4dad0c99e0a5b94d58fbx'
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: "4db8d02bfff84b4dad0c99e0a5b94d58.fbx" }}
          >
            <group name='Object_2' userData={{ name: "Object_2" }}>
              <group name='RootNode' userData={{ name: "RootNode" }}>
                <group
                  name='planetarioplanetario'
                  userData={{ name: "planetario:planetario" }}
                >
                  <group
                    name='planetarioJ_PITER'
                    rotation={[0, -Math.PI / 4, 0]}
                    userData={{ name: "planetario:J_PITER" }}
                  >
                    <group name='Object_6' userData={{ name: "Object_6" }}>
                      {/* <primitive object={glb.nodes._rootJoint} /> */}
                      <instances.Object
                        name='Object_8'
                        userData={{ name: "Object_8" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioMARTE'
                    rotation={[0, Math.PI / 4, 0]}
                    userData={{ name: "planetario:MARTE" }}
                  >
                    <group name='Object_11' userData={{ name: "Object_11" }}>
                      {/* <primitive object={glb.nodes._rootJoint_1} /> */}
                      <instances.Object1
                        name='Object_13'
                        userData={{ name: "Object_13" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioMERCURIO'
                    userData={{ name: "planetario:MERCURIO" }}
                  >
                    <group name='Object_16' userData={{ name: "Object_16" }}>
                      {/* <primitive object={glb.nodes._rootJoint_2} /> */}
                      <instances.Object2
                        name='Object_18'
                        userData={{ name: "Object_18" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioNEPTUNO'
                    rotation={[0, Math.PI / 6, 0]}
                    userData={{ name: "planetario:NEPTUNO" }}
                  >
                    <group name='Object_21' userData={{ name: "Object_21" }}>
                      {/* <primitive object={glb.nodes._rootJoint_3} /> */}
                      <instances.Object3
                        name='Object_23'
                        userData={{ name: "Object_23" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioPLUTON'
                    rotation={[0, -1.31, 0]}
                    userData={{ name: "planetario:PLUTON" }}
                  >
                    <group name='Object_26' userData={{ name: "Object_26" }}>
                      {/* <primitive object={glb.nodes._rootJoint_4} /> */}
                      <instances.Object4
                        name='Object_28'
                        userData={{ name: "Object_28" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioSATURNO'
                    rotation={[-Math.PI, -0.26, -Math.PI]}
                    userData={{ name: "planetario:SATURNO" }}
                  >
                    <group name='Object_33' userData={{ name: "Object_33" }}>
                      {/* <primitive object={glb.nodes._rootJoint_5} /> */}
                      <instances.Object5
                        name='Object_35'
                        userData={{ name: "Object_35" }}
                      />
                      <instances.Object6
                        name='Object_36'
                        userData={{ name: "Object_36" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioTIERRA'
                    rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}
                    userData={{ name: "planetario:TIERRA" }}
                  >
                    <group name='Object_39' userData={{ name: "Object_39" }}>
                      <group
                        name='planetarioHUESO_LUNA'
                        position={[1843.27, 0, -1.31]}
                        userData={{ name: "planetario:HUESO_LUNA" }}
                      >
                        <group
                          name='planetarioLUNA'
                          userData={{ name: "planetario:LUNA" }}
                        >
                          <instances.PlanetarioLUNALUNA
                            name='planetarioLUNA_LUNA_0'
                            userData={{ name: "planetario:LUNA_LUNA_0" }}
                          />
                        </group>
                      </group>
                      {/* <primitive object={glb.nodes._rootJoint_6} /> */}
                      <instances.Object7
                        name='Object_41'
                        userData={{ name: "Object_41" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioURANO'
                    rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                    userData={{ name: "planetario:URANO" }}
                  >
                    <group name='Object_47' userData={{ name: "Object_47" }}>
                      {/* <primitive object={glb.nodes._rootJoint_7} /> */}
                      <instances.Object8
                        name='Object_49'
                        userData={{ name: "Object_49" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetarioVENUS'
                    rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
                    userData={{ name: "planetario:VENUS" }}
                  >
                    <group name='Object_52' userData={{ name: "Object_52" }}>
                      {/* <primitive object={glb.nodes._rootJoint_8} /> */}
                      <instances.Object9
                        name='Object_55'
                        userData={{ name: "Object_55" }}
                      />
                    </group>
                  </group>
                  <group
                    name='planetariopolymsh'
                    userData={{ name: "planetario:polymsh" }}
                  >
                    <instances.Planetariopolymsharos
                      name='planetariopolymsh_aros_0'
                      userData={{ name: "planetario:polymsh_aros_0" }}
                    />
                  </group>
                  <group
                    name='planetariosolsol'
                    userData={{ name: "planetario:sol:sol" }}
                  >
                    <group
                      name='planetariosolsol_ncl1_1'
                      userData={{ name: "planetario:sol:sol_ncl1_1" }}
                    >
                      <group
                        name='planetariosolsphere'
                        userData={{ name: "planetario:sol:sphere" }}
                      >
                        <instances.Planetariosolspheresol
                          name='planetariosolsphere_sol_1_0'
                          userData={{ name: "planetario:sol:sphere_sol_1_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolsphere1'
                        userData={{ name: "planetario:sol:sphere1" }}
                      >
                        <instances.Planetariosolspheresol1
                          name='planetariosolsphere1_sol_2_0'
                          userData={{ name: "planetario:sol:sphere1_sol_2_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolsphere2'
                        userData={{ name: "planetario:sol:sphere2" }}
                      >
                        <instances.Planetariosolspheresol2
                          name='planetariosolsphere2_sol_1_0'
                          userData={{ name: "planetario:sol:sphere2_sol_1_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolsphere3'
                        userData={{ name: "planetario:sol:sphere3" }}
                      >
                        <instances.Planetariosolspheresol3
                          name='planetariosolsphere3_sol_2_0'
                          userData={{ name: "planetario:sol:sphere3_sol_2_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolsphere4'
                        userData={{ name: "planetario:sol:sphere4" }}
                      >
                        <instances.Planetariosolspheresol4
                          name='planetariosolsphere4_sol_1_0'
                          userData={{ name: "planetario:sol:sphere4_sol_1_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached'
                        userData={{ name: "planetario:sol:polymsh_detached" }}
                      >
                        <instances.Planetariosolpolymshdetachedcorona
                          name='planetariosolpolymsh_detached_corona1_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached_corona1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached1'
                        userData={{ name: "planetario:sol:polymsh_detached1" }}
                      >
                        <instances.Planetariosolpolymshdetachedcorona1
                          name='planetariosolpolymsh_detached1_corona1_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached1_corona1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached2'
                        userData={{ name: "planetario:sol:polymsh_detached2" }}
                      >
                        <instances.Planetariosolpolymshdetachedcorona2
                          name='planetariosolpolymsh_detached2_corona1_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached2_corona1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached3'
                        userData={{ name: "planetario:sol:polymsh_detached3" }}
                      >
                        <instances.Planetariosolpolymshdetachedcorona3
                          name='planetariosolpolymsh_detached3_corona1_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached3_corona1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolnucleo1'
                        userData={{ name: "planetario:sol:nucleo1" }}
                      >
                        <instances.Planetariosolnucleonucleo
                          name='planetariosolnucleo1_nucleo_1_0'
                          userData={{
                            name: "planetario:sol:nucleo1_nucleo_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolnucleo2'
                        userData={{ name: "planetario:sol:nucleo2" }}
                      >
                        <instances.PlanetariosolnucleoMaterial
                          name='planetariosolnucleo2_Material_0'
                          userData={{
                            name: "planetario:sol:nucleo2_Material_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolnucleo3'
                        userData={{ name: "planetario:sol:nucleo3" }}
                      >
                        <instances.Planetariosolnucleonucleo1
                          name='planetariosolnucleo3_nucleo_1_0'
                          userData={{
                            name: "planetario:sol:nucleo3_nucleo_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolnucleo4'
                        userData={{ name: "planetario:sol:nucleo4" }}
                      >
                        <instances.PlanetariosolnucleoMaterial1
                          name='planetariosolnucleo4_Material_0'
                          userData={{
                            name: "planetario:sol:nucleo4_Material_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolllamarada_1'
                        userData={{ name: "planetario:sol:llamarada_1" }}
                      >
                        <instances.Planetariosolllamaradallamarada
                          name='planetariosolllamarada_1_llamarada_1_0'
                          userData={{
                            name: "planetario:sol:llamarada_1_llamarada_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolllamarada_2'
                        scale={0.9}
                        userData={{ name: "planetario:sol:llamarada_2" }}
                      >
                        <instances.Planetariosolllamaradallamarada1
                          name='planetariosolllamarada_2_llamarada_1_0'
                          userData={{
                            name: "planetario:sol:llamarada_2_llamarada_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolllamarada_3'
                        scale={0.9}
                        userData={{ name: "planetario:sol:llamarada_3" }}
                      >
                        <instances.Planetariosolllamaradallamarada2
                          name='planetariosolllamarada_3_llamarada_1_0'
                          userData={{
                            name: "planetario:sol:llamarada_3_llamarada_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolllamarada_4'
                        scale={0.9}
                        userData={{ name: "planetario:sol:llamarada_4" }}
                      >
                        <instances.Planetariosolllamaradallamarada3
                          name='planetariosolllamarada_4_llamarada_1_0'
                          userData={{
                            name: "planetario:sol:llamarada_4_llamarada_1_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached4'
                        userData={{ name: "planetario:sol:polymsh_detached4" }}
                      >
                        <instances.PlanetariosolpolymshdetachedSuperfie
                          name='planetariosolpolymsh_detached4_Superfie_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached4_Superfie_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached5'
                        userData={{ name: "planetario:sol:polymsh_detached5" }}
                      >
                        <instances.PlanetariosolpolymshdetachedSuperfie1
                          name='planetariosolpolymsh_detached5_Superfie_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached5_Superfie_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached6'
                        userData={{ name: "planetario:sol:polymsh_detached6" }}
                      >
                        <instances.PlanetariosolpolymshdetachedSuperfie2
                          name='planetariosolpolymsh_detached6_Superfie_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached6_Superfie_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolpolymsh_detached7'
                        userData={{ name: "planetario:sol:polymsh_detached7" }}
                      >
                        <instances.PlanetariosolpolymshdetachedSuperfie3
                          name='planetariosolpolymsh_detached7_Superfie_0'
                          userData={{
                            name: "planetario:sol:polymsh_detached7_Superfie_0",
                          }}
                        />
                      </group>
                      <group
                        name='planetariosolsphere5'
                        userData={{ name: "planetario:sol:sphere5" }}
                      >
                        <instances.Planetariosolspheresol5
                          name='planetariosolsphere5_sol_1_0'
                          userData={{ name: "planetario:sol:sphere5_sol_1_0" }}
                        />
                      </group>
                      <group
                        name='planetariosolnucleo'
                        userData={{ name: "planetario:sol:nucleo" }}
                      >
                        <instances.Planetariosolnucleoamarillo
                          name='planetariosolnucleo_amarillo_0'
                          userData={{
                            name: "planetario:sol:nucleo_amarillo_0",
                          }}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(
  import.meta.env.VITE_ASSETS_PATH + "/models/solar_system_animation.glb"
);
